# Generated by Django 5.1.3 on 2024-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('activity', models.IntegerField(choices=[(0, 'Registro de Produto'), (1, 'Registro de Cliente'), (2, 'Registro de Pedido'), (3, 'Registro de Carrinho'), (4, 'Atualização de Produto'), (5, 'Atualização de Cliente'), (6, 'Atualização de Pedido'), (7, 'Atualização de Carrinho'), (8, 'Exclusão de Produto'), (9, 'Exclusão de Cliente'), (10, 'Exclusão de Pedido'), (11, 'Exclusão de Carrinho')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
