# Generated by Django 5.1.3 on 2024-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço do cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone do cliente'),
        ),
    ]
