# Generated by Django 5.1.3 on 2024-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cliente_address_alter_cliente_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Inserir'), (1, 'Atualizar'), (2, 'Excluir'), (3, 'Venda')]),
        ),
    ]
