# Generated by Django 5.1.3 on 2024-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_historic_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='taxa',
            field=models.FloatField(default=0),
        ),
    ]
